# Site settings
title: Umut Ergin | Cyber Security
description: ""
url: "https://umutergin.github.io"
author:
  name: "Umut Ergin"
  email: "umutergincs@gmail.com"
  url: "https://umutergin.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate


# Options
custom_header: false
custom_nav_footer: false
reverse: false
